name: Docker Image CI

on:
  push:
    branches: [ 3.4.1 ]
  pull_request:
    branches: [ 3.4.1 ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: moresci/mastodon
          tags: 3.4.1
